spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mao?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username : root
    password : root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8082